In [23]:
import pandas as pd
titanicdata=pd.read_csv("./tested.csv")
titanicdata


PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [24]:
titanicdata.isna()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
413        False     False   False  False  False   True  False  False   False   
414        False     False   False  False  False  False  False  False   False   
415        False     False   False  False  False  False  False  False   False   
416        False     False   False  False  False   True  False  False   False   
417        False     False   False  False  False   True  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False   True     False  
2    False   True     False  
3    False   True     False  
4    False   True     False  
..     ...    ...       ...  
413  False   True     False  
414  False  False     False  
415  False   True     False  
416  False   True     False  
417  False   True     False  

[418 rows x 12 columns]

In [25]:
titanicdata.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [26]:
titanicdata['Age'].isna().sum()

86

In [27]:
titanicdata['Cabin'].isna().sum()

327

In [28]:
titanicdata['Embarked'].isna().sum()

0

In [29]:
titanicdata['Age'].fillna(titanicdata['Age'].mean(), inplace=True)

In [30]:
titanicdata['Age']

0      34.50000
1      47.00000
2      62.00000
3      27.00000
4      22.00000
         ...   
413    30.27259
414    39.00000
415    38.50000
416    30.27259
417    30.27259
Name: Age, Length: 418, dtype: float64

In [31]:
titanicdata['Embarked'].fillna(titanicdata['Embarked'].mode()[0], inplace=True)

In [32]:
titanicdata['Embarked']

0      Q
1      S
2      Q
3      S
4      S
      ..
413    S
414    C
415    S
416    S
417    C
Name: Embarked, Length: 418, dtype: object

In [33]:

titanicdata['Cabin'].isna().count()

418

In [34]:
titanicdata.drop(columns=['Cabin'], inplace=True)

In [35]:
titanicdata

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex       Age  SibSp  \
0                                Kelly, Mr. James    male  34.50000      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.00000      1   
2                       Myles, Mr. Thomas Francis    male  62.00000      0   
3                                Wirz, Mr. Albert    male  27.00000      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.00000      1   
..                                            ...     ...       ...    ...   
413                            Spector, Mr. Woolf    male  30.27259      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.00000      0   
415                  Saether, Mr. Simon Sivertsen    male  38.50000      0   
416                           Ware, Mr. Frederick    male  30.27259      0   
417                      Peter, Master. Michael J    male  30.27259      1   

     Parch              Ticket      Fare Embarked  
0        0              330911    7.8292        Q  
1        0              363272    7.0000        S  
2        0              240276    9.6875        Q  
3        0              315154    8.6625        S  
4        1             3101298   12.2875        S  
..     ...                 ...       ...      ...  
413      0           A.5. 3236    8.0500        S  
414      0            PC 17758  108.9000        C  
415      0  SOTON/O.Q. 3101262    7.2500        S  
416      0              359309    8.0500        S  
417      1                2668   22.3583        C  

[418 rows x 11 columns]

In [36]:
titanicdata['Sex'] = titanicdata['Sex'].map({'male': 0, 'female': 1})

In [37]:
titanicdata['Sex']

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Sex, Length: 418, dtype: int64

In [38]:
titanicdata['Embarked'] = titanicdata['Embarked'].map({'C': 0, 'Q': 1, 'S': 2})

In [39]:
titanicdata['Embarked']

0      1
1      2
2      1
3      2
4      2
      ..
413    2
414    0
415    2
416    2
417    0
Name: Embarked, Length: 418, dtype: int64

In [40]:
titanicdata['FamilySize'] =titanicdata['SibSp'] + titanicdata['Parch'] + 1

In [41]:
titanicdata

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name  Sex       Age  SibSp  \
0                                Kelly, Mr. James    0  34.50000      0   
1                Wilkes, Mrs. James (Ellen Needs)    1  47.00000      1   
2                       Myles, Mr. Thomas Francis    0  62.00000      0   
3                                Wirz, Mr. Albert    0  27.00000      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1  22.00000      1   
..                                            ...  ...       ...    ...   
413                            Spector, Mr. Woolf    0  30.27259      0   
414                  Oliva y Ocana, Dona. Fermina    1  39.00000      0   
415                  Saether, Mr. Simon Sivertsen    0  38.50000      0   
416                           Ware, Mr. Frederick    0  30.27259      0   
417                      Peter, Master. Michael J    0  30.27259      1   

     Parch              Ticket      Fare  Embarked  FamilySize  
0        0              330911    7.8292         1           1  
1        0              363272    7.0000         2           2  
2        0              240276    9.6875         1           1  
3        0              315154    8.6625         2           1  
4        1             3101298   12.2875         2           3  
..     ...                 ...       ...       ...         ...  
413      0           A.5. 3236    8.0500         2           1  
414      0            PC 17758  108.9000         0           1  
415      0  SOTON/O.Q. 3101262    7.2500         2           1  
416      0              359309    8.0500         2           1  
417      1                2668   22.3583         0           3  

[418 rows x 12 columns]

In [42]:
# Drop unnecessary columns
titanicdata.drop(columns=['Name', 'Ticket', 'PassengerId'], inplace=True)

In [43]:
titanicdata

Survived  Pclass  Sex       Age  SibSp  Parch      Fare  Embarked  \
0           0       3    0  34.50000      0      0    7.8292         1   
1           1       3    1  47.00000      1      0    7.0000         2   
2           0       2    0  62.00000      0      0    9.6875         1   
3           0       3    0  27.00000      0      0    8.6625         2   
4           1       3    1  22.00000      1      1   12.2875         2   
..        ...     ...  ...       ...    ...    ...       ...       ...   
413         0       3    0  30.27259      0      0    8.0500         2   
414         1       1    1  39.00000      0      0  108.9000         0   
415         0       3    0  38.50000      0      0    7.2500         2   
416         0       3    0  30.27259      0      0    8.0500         2   
417         0       3    0  30.27259      1      1   22.3583         0   

     FamilySize  
0             1  
1             2  
2             1  
3             1  
4             3  
..          ...  
413           1  
414           1  
415           1  
416           1  
417           3  

[418 rows x 9 columns]

In [49]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer
# Define features and target variable
X = titanicdata[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Embarked', 'FamilySize']]
y = titanicdata['Pclass']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize the model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 1.0
Confusion Matrix:
[[21  0  0]
 [ 0 21  0]
 [ 0  0 42]]
Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00        21
           3       1.00      1.00      1.00        42

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84



Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          1
Embarked      0
FamilySize    0
dtype: int64